apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log "configmaps" at RequestResponse level for user minikube-user
  - level: RequestResponse
    users: ["minikube-user"]
    resources:
    - groups: ""
      resources: ["configmaps"]
